import Link from 'next/link';
import {ArrowLeft, History} from 'lucide-react';

import {PageContainer} from '@/components/layout';
import GlassPanel from '@/components/shared/GlassPanel';
import {Button} from '@/components/ui/button';

import RecommendationHistoryList from './_components/RecommendationHistoryList';

export default function AIHistoryPage() {
    return (
        <main className="page-shell">
            <PageContainer className="space-y-8 py-8">
                <Button asChild variant="ghost" size="sm">
                    <Link href="/ai">
                        <ArrowLeft className="size-4" />
                        Back to AI advisor
                    </Link>
                </Button>

                <GlassPanel variant="elevated">
                    <div className="flex items-center gap-4">
                        <div className="flex size-12 items-center justify-center rounded-2xl bg-primary/10 text-primary">
                            <History className="size-6" />
                        </div>

                        <div>
                            <p className="eyebrow">AI history</p>

                            <h1 className="page-title mt-2">
                                Previous recommendations
                            </h1>

                            <p className="body-text mt-2">
                                Browse recommendations generated by the AI
                                advisor.
                            </p>
                        </div>
                    </div>
                </GlassPanel>

                <RecommendationHistoryList />
            </PageContainer>
        </main>
    );
}
