import Link from 'next/link';
import {getServerCookieHeader} from '@/lib/auth/server-auth';
import {ArrowLeft, History} from 'lucide-react';

import {PageContainer} from '@/components/layout';
import GlassPanel from '@/components/shared/GlassPanel';
import {Button} from '@/components/ui/button';
import AiService from '@/services/ai.service';

import RecommendationHistoryList from './_components/RecommendationHistoryList';

export default async function AIHistoryPage() {
    const cookieHeader = await getServerCookieHeader();

    const recommendations = await AiService.getRecommendations(
        'car-recommendation',
        {
            headers: {
                Cookie: cookieHeader,
            },
        },
    );

    return (
        <main className="page-shell">
            <PageContainer className="space-y-8 py-8 md:py-10">
                <Button
                    asChild
                    variant="ghost"
                    size="sm"
                    className="-ml-3 w-fit text-muted-foreground hover:text-foreground"
                >
                    <Link href="/ai">
                        <ArrowLeft className="size-4" aria-hidden="true" />
                        Back to AI advisor
                    </Link>
                </Button>

                <GlassPanel variant="elevated">
                    <div className="flex items-center gap-4">
                        <div className="flex size-12 items-center justify-center rounded-2xl bg-primary/10 text-primary">
                            <History className="size-6" aria-hidden="true" />
                        </div>

                        <div>
                            <p className="eyebrow">AI history</p>

                            <h1 className="page-title mt-2">
                                Previous recommendations
                            </h1>

                            <p className="body-text mt-2">
                                Browse car recommendations generated by the
                                global AI advisor.
                            </p>
                        </div>
                    </div>
                </GlassPanel>

                <RecommendationHistoryList recommendations={recommendations} />
            </PageContainer>
        </main>
    );
}
